### ISSUE TITLE
adobe-only-user-list broken since 2.3

### ISSUE THREAD

**Issue by vossen-adobe** [adobe-apiplatform/user-sync.py#477]
Intially bug introduced in this commit: cb82a0ab513ff38b37c70830faf849f458816dc7

The option for adobe-only-user-list seems not to have worked since the additional groups feature.  When using the option, no directory is pulled into app.py.   This causes the statement on line 317 to produce a null pointer on the state attribute:

directory_connector.state.additional_group_filters = additional_group_filters

Solution is simple - the additional group filter should only be assigned when a connector exists, since it doesn't apply to the adobe-only-user-list.  The output is:

2019-04-10 14:48:42 7064 INFO main - -t -c ..\test_config\user-sync-config.yml --adobe-only-user-list ..\test_config\remove-list.csv
2019-04-10 14:48:42 7064 INFO main - -------------------------------------
2019-04-10 14:48:42 7064 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "D:/Repositories/adobe/user-sync-fork/user_sync/app.py", line 85, in main
    begin_work(config_loader)
  File "D:/Repositories/adobe/user-sync-fork/user_sync/app.py", line 322, in begin_work
    directory_connector.state.additional_group_filters = additional_group_filters
AttributeError: 'NoneType' object has no attribute 'state'
2019-04-10 14:48:42 7064 INFO main - ========== End Run (User Sync version: 2.4.3) (Total time: 0:00:00)

**Comment by adorton-adobe** [comment]
Can you look at #459 and tell me if that fixes this issue?  I think it may.

**Comment by vossen-adobe** [comment]
Indeed - fixed by #459!

**Comment by bajwa-adobe** [comment]
`adobe-only-user-list` seems still broken on my side in latest build 2.5.0rc2 but different error. And it is also failing on v2.4.3 and gives different error. 

Environment: Windows/Python 3.6.8 

I got following error on v2.5.0rc2:

```
>python user-sync.pex -t --adobe-only-user-list remove-list.csv --adobe-only-user-action remove
2019-05-14 15:04:17 21300 INFO config - Using main config file: user-sync-config.yml (encoding utf8)
2019-05-14 15:04:17 21300 INFO config - Adobe-only user list specified, ignoring 'users' setting
2019-05-14 15:04:17 21300 ERROR main - Unhandled exception
Traceback (most recent call last):
  File "c:\pex\install\user_sync-2.5.0rc2-py3-none-any.whl.130c9ffbff8526cb9012602829f0e3cb029e29b5\user_sync-2.5.0rc2-py3-none-any.whl\user_sync\app.py", line 160, in sync
    config_loader = user_sync.config.ConfigLoader(kwargs)
  File "c:\pex\install\user_sync-2.5.0rc2-py3-none-any.whl.130c9ffbff8526cb9012602829f0e3cb029e29b5\user_sync-2.5.0rc2-py3-none-any.whl\user_sync\config.py", line 71, in __init__
    self.invocation_options = self.load_invocation_options()
  File "c:\pex\install\user_sync-2.5.0rc2-py3-none-any.whl.130c9ffbff8526cb9012602829f0e3cb029e29b5\user_sync-2.5.0rc2-py3-none-any.whl\user_sync\config.py", line 207, in load_invocation_options
    if options['stray_list_output_path'] is not None:
KeyError: 'stray_list_output_path'
```

I got following error on v2.4.3:

```
>python user-sync.pex -t --adobe-only-user-list remove-list.csv --adobe-only-user-action remove
2019-05-15 09:59:59 23396 INFO config - Using main config file: user-sync-config.yml (encoding utf8)
c:\pex\install\user_sync-2.4.3-py3-none-any.whl.1c05209bb7835026761c4d6bd54d6eba23e6e900\user_sync-2.4.3-py3-none-any.whl\user_sync\config.py:957: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yml = yaml.load(byte_string.decode(cls.config_encoding, 'strict'))
2019-05-15 09:59:59 23396 CRITICAL main - You cannot specify both a --users arg and an --adobe-only-user-list arg
```

Here is my config:
```
adobe_users:
  exclude_identity_types:
    - adobeID
  exclude_adobe_groups: null
  exclude_users:
    - .*@adobe.com
  connectors:
    umapi: connector-umapi.yml
directory_users:
  user_identity_type: federatedID
  default_country_code: GB
  connectors:
    ldap: connector-ldap.yml
  groups:
    - directory_group: InDesign Users
      adobe_groups:
        - InDesign
    - directory_group: Photoshop Users
      adobe_groups:
        - Photoshop
limits:
  max_adobe_only_users: 200
logging:
  log_to_file: true
  file_log_directory: logs
  file_log_name_format: '{:%Y-%m-%d}.log'
  file_log_level: debug
  console_log_level: info
invocation_defaults:
  adobe_only_user_action: preserve
  adobe_only_user_list: null
  connector: ldap
  process_groups: Yes
  strategy: sync
  test_mode: No
  update_user_info: No
  user_filter: null
  users: mapped
``` 

Any ideas what is wrong?

**Comment by Luci2015** [comment]
The previous fix worked, but the config.py got re-worked and the initialisation of stray_list_output_path is now required.
I'll add a new PR to fix this again.
